ProdMan/Controllers/BtwController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProdMan_Models;
using ProdMan_Models.Tables;

namespace ProdMan.Controllers
{
    public class BtwController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Btw
        public ActionResult Index()
        {
            return View(db.Btws.ToList());
        }

        // GET: Btw/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Btw btw = db.Btws.Find(id);
            if (btw == null)
            {
                return HttpNotFound();
            }
            return View(btw);
        }

        // GET: Btw/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Btw/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,BtwNaam,BtwValue")] Btw btw)
        {
            if (ModelState.IsValid)
            {
                db.Btws.Add(btw);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(btw);
        }

        // GET: Btw/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Btw btw = db.Btws.Find(id);
            if (btw == null)
            {
                return HttpNotFound();
            }
            return View(btw);
        }

        // POST: Btw/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BtwNaam,BtwValue")] Btw btw)
        {
            if (ModelState.IsValid)
            {
                db.Entry(btw).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(btw);
        }

        // GET: Btw/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Btw btw = db.Btws.Find(id);
            if (btw == null)
            {
                return HttpNotFound();
            }
            return View(btw);
        }

        // POST: Btw/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Btw btw = db.Btws.Find(id);
            db.Btws.Remove(btw);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProdMan/Views/Btw/Create.cshtml
@model ProdMan_Models.Tables.Btw

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Btw</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BtwNaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BtwNaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BtwNaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BtwValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BtwValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BtwValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProdMan/Views/Btw/Delete.cshtml
@model ProdMan_Models.Tables.Btw

@{
    ViewBag.Title = "Delete";
}

<br />
<div class="alert alert-success">
    <strong>Weet u zeker dat u dit btw soort wilt verwijderen?</strong> Het is hierna niet meer mogelijk om dit ongedaan te maken!
</div>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BtwNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BtwNaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BtwValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BtwValue)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ja" class="btn btn-danger" />
            @Html.ActionLink("Nee", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-success" })
        </div>
    }
</div>

ProdMan/Views/Btw/Details.cshtml
@model ProdMan_Models.Tables.Btw

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Btw</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BtwNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BtwNaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BtwValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BtwValue)
        </dd>

    </dl>
</div>
<p>    
    @Html.ActionLink("Bewerken", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Terug", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-primary" })
    @Html.ActionLink("Verwijderen", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" })
</p>

ProdMan/Views/Btw/Edit.cshtml
@model ProdMan_Models.Tables.Btw

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Btw</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BtwNaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BtwNaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BtwNaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BtwValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BtwValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BtwValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProdMan/Views/Btw/Index.cshtml
@using ProdMan_Models.Tables
@model IEnumerable<ProdMan_Models.Tables.Btw>

@{
    ViewBag.Title = "Index";
}

<h2>Btw</h2>

<p>
    @Html.ActionLink("Nieuw btw percentage", "Create", null, new { @class = "btn btn-primary" })
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BtwNaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BtwValue)
        </th>       
    </tr>

@foreach (var item in Model) {
    Btw btw = item;
    <tr>
        <td onclick="location.href = '@Url.Action("Details", "Btw", new { id = item.Id })'" style="cursor: pointer;">
            @Html.DisplayFor(modelItem => btw.BtwNaam)
        </td>
        <td onclick="location.href = '@Url.Action("Details", "Btw", new { id = item.Id })'" style="cursor: pointer;">
            @Html.DisplayFor(modelItem => btw.BtwValue)
        </td>
    </tr>
}

</table>