ProdMan/Controllers/CalculatorController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ProdMan_Models;
using ProdMan_Models.Dal;
using ProdMan_Models.Tables;
using ProdMan_Models.View;

namespace ProdMan.Controllers
{
    public class CalculatorController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly OverviewDal _overviewDal = new OverviewDal();

        // GET: Overview
        public ActionResult Index()
        {
            var oReturn = new OverView
            {
                Leveranciers = _overviewDal.GetAllLeveranciers(),
                Products = _overviewDal.GetAllProducts(),
                ProductGroeps = _overviewDal.GetAllProductGroep()
            };

            return View(oReturn);
        }

        // /Calculator/JsonResultProductList/
        [HttpGet]
        public JsonResult JsonResultProductList(bool o = true, bool b = true, bool a = true)
        {
            List<Product> jReturn = _db.Producten.ToList();

            return Json(jReturn, JsonRequestBehavior.AllowGet);
        }
    }
}

ProdMan/Controllers/OverviewController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ProdMan_Models;
using ProdMan_Models.Dal;
using ProdMan_Models.Tables;
using ProdMan_Models.View;

namespace ProdMan.Controllers
{
    public class OverviewController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly OverviewDal _overviewDal = new OverviewDal();

        // GET: Overview
        public ActionResult Index()
        {
            var oReturn = new OverView
            {
                Leveranciers = _overviewDal.GetAllLeveranciers(),
                Products = _overviewDal.GetAllProducts(),
                ProductGroeps = _overviewDal.GetAllProductGroep()
            };

            return View(oReturn);            
        }


    }
}

ProdMan/Controllers/ProductEigenschappenController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProdMan_Models;
using ProdMan_Models.Tables;

namespace ProdMan.Controllers
{
    public class ProductEigenschappenController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProductEigenschappen
        public ActionResult Index()
        {
            return View(db.ProductEigenschappen.ToList());
        }

        // GET: ProductEigenschappen/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductEigenschappen productEigenschappen = db.ProductEigenschappen.Find(id);
            if (productEigenschappen == null)
            {
                return HttpNotFound();
            }
            return View(productEigenschappen);
        }

        // GET: ProductEigenschappen/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductEigenschappen/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naam,Nummer,PrijsFactor,Toeslag")] ProductEigenschappen productEigenschappen)
        {
            if (ModelState.IsValid)
            {
                db.ProductEigenschappen.Add(productEigenschappen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productEigenschappen);
        }

        // GET: ProductEigenschappen/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductEigenschappen productEigenschappen = db.ProductEigenschappen.Find(id);
            if (productEigenschappen == null)
            {
                return HttpNotFound();
            }
            return View(productEigenschappen);
        }

        // POST: ProductEigenschappen/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naam,Nummer,PrijsFactor,Toeslag")] ProductEigenschappen productEigenschappen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productEigenschappen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productEigenschappen);
        }

        // GET: ProductEigenschappen/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductEigenschappen productEigenschappen = db.ProductEigenschappen.Find(id);
            if (productEigenschappen == null)
            {
                return HttpNotFound();
            }
            return View(productEigenschappen);
        }

        // POST: ProductEigenschappen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductEigenschappen productEigenschappen = db.ProductEigenschappen.Find(id);
            db.ProductEigenschappen.Remove(productEigenschappen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProdMan/Controllers/ProductGroepenController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProdMan_Models;
using ProdMan_Models.Tables;

namespace ProdMan.Controllers
{
    public class ProductGroepenController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        // GET: ProductGroepen
        public ActionResult Index()
        {
            return View(_db.ProductGroepen.ToList());
        }

        // GET: ProductGroepen/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductGroep productGroep = _db.ProductGroepen.Find(id);
            if (productGroep == null)
            {
                return HttpNotFound();
            }
            return View(productGroep);
        }

        // GET: ProductGroepen/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductGroepen/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nummer,Naam")] ProductGroep productGroep)
        {
            if (_db.ProductGroepen.Any(o => o.Nummer == productGroep.Nummer))
            {                
                // Number is already used
                var mod = ModelState.First(c => c.Key == "Nummer");
                mod.Value.Errors.Add("Dit nummer is al in gebruik!");
            }

            if (!ModelState.IsValid)
            {
                // Model not valid!
                return View(productGroep);
            }

            _db.ProductGroepen.Add(productGroep);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: ProductGroepen/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductGroep productGroep = _db.ProductGroepen.Find(id);
            if (productGroep == null)
            {
                return HttpNotFound();
            }
            return View(productGroep);
        }

        // POST: ProductGroepen/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nummer,Naam")] ProductGroep productGroep)
        {
            if (_db.ProductGroepen.Any(o => o.Nummer == productGroep.Nummer && o.Id != productGroep.Id))
            {
                // Number is already used
                var mod = ModelState.First(c => c.Key == "Nummer");
                mod.Value.Errors.Add("Dit nummer is al in gebruik!");
            }

            if (!ModelState.IsValid)
            {
                // Model is not Valid
                return View(productGroep);
            }

            _db.Entry(productGroep).State = EntityState.Modified;
            _db.SaveChanges();
            
            return RedirectToAction("Index");
        }

        // GET: ProductGroepen/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductGroep productGroep = _db.ProductGroepen.Find(id);
            if (productGroep == null)
            {
                return HttpNotFound();
            }
            return View(productGroep);
        }

        // POST: ProductGroepen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductGroep productGroep = _db.ProductGroepen.Find(id);
            _db.ProductGroepen.Remove(productGroep);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProdMan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Product Manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Offerte", "Index", "Calculator")</li>
                        <li>@Html.ActionLink("Overzicht", "Index", "Overview")</li>                        
                    </ul>
                    <ul class="nav navbar-nav navbar">
                                                
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Onderhoud <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Product", "Index", "Product")</li>
                                <li>@Html.ActionLink("Productgroep", "Index", "ProductGroepen")</li>
                                <li>@Html.ActionLink("Product Eigenschappen", "Index", "ProductEigenschappen")</li>
                                <li>@Html.ActionLink("Product Eigenschappen Koppelingen", "Index", "ProductEigenschappenKoppelings")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Leveranciers", "Index", "Leveranciers")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Btw", "Index", "Btw")</li>

                            </ul>
                        </li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            

            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Fiek Buurman</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>